### ISSUE TITLE
What code should I paste into configuration.yaml?

### ISSUE THREAD

**Issue by matata86** [BeryJu/hass-ticktick#29]
Please what code should I paste into configuration.yaml to login to TickTick?
Thank you.

**Comment by BeryJu** [comment]
Hi,

this component is not configured by yaml, instead by going navigating to Integrations in the Web Interface. There you can add the Integration by clicking the Plus Icon, and select TickTick.

**Comment by BeryJu** [comment]
Allthough I did notice that the input's labels are broken, so I'll try to fix that

**Comment by matata86** [comment]
Thank you. Its works. But every task has due date today. Is possible set deu date to none?

I try:
service: ticktick.add_task
data:
  title: asdasdasdasd
  due_date: none

But not works.

**Comment by BeryJu** [comment]
yes currently it defaults to due_date as today, I will add an option to change this.

**Comment by BeryJu** [comment]
@matata86 I've just published the new version 1.1, this removes the default due_date and allows you to set a custom one.

**Comment by matata86** [comment]
Awesome! Thx
