### ISSUE TITLE
Confguring login and passowrd

### ISSUE THREAD

**Issue by fkirill** [BeryJu/hass-ticktick#51]
How do I configure login and password for ticktick? If not in .yaml, where do I enter this?

**Comment by BeryJu** [comment]
Under "Configuration" -> "Integrations", click the Plus button in the bottom right and enter ticktick in the search field. This will prompt you for the credentials and configure the integration.

**Comment by fkirill** [comment]
No, it doesn't on my installation.
I click on tick-tick, it shows me an info screen (no inputs), and a "Install this repository in HACS" button. I click it.
Next, it shows me a version choice dialog (variants are 1.0 and 1.1), no other inputs. I click "Install".
Next, it just tells me that I need to restart HASS.

No username or password prompt anywhere.

**Comment by BeryJu** [comment]
After you've installed it, have you restarted HASS? After the restart, you should go to `http://your-hass:8123/config/integrations` and it should be able to add it.

If after you've installed it and restarted HASS it still doesn't show, could you post your logs here?

**Comment by fkirill** [comment]
Okay, figured it out, thank you, didn't realize this is a multi-step process.

Might make sense to document that briefly for the newbies like me who never dealt with HACS before.
