### ISSUE TITLE
Trouble with setup/configuration

### ISSUE THREAD

**Issue by baukeposthuma** [BeryJu/hass-ticktick#57]
Hi There!

When I install this integration with HACS, I don't see any ticktick service or components appear. Maybe I'm doing something wrong? 

Thanks!

**Comment by BeryJu** [comment]
Hi,

after installing the integration with HACS, and restarting HASS, you should be able to add the TickTick integration in the Integrations Menu:

![image](https://user-images.githubusercontent.com/1932513/109725153-02b86980-7bb1-11eb-8c38-b61b733492ee.png)

**Comment by baukeposthuma** [comment]
Found it! Thanks!

Is there a way to list all tasks in a project?

**Comment by BeryJu** [comment]
> Is there a way to list all tasks in a project?

There isn't currently, no. I assume you're trying to build an Open task list for your dashboard?

**Comment by baukeposthuma** [comment]
Yes that's what I'm trying to build
